Bokeh to Plotly
tardis-sn/tardis-refdata pull request #77
Opened 2024-04-15 10:47 UTC by atharva-2001

### :pencil: Description

**Type:** :beetle: `bugfix` 

Resolves https://github.com/tardis-sn/tardis/issues/2162 

### :pushpin: Resources

### :vertical_traffic_light: Testing

How did you test these changes?

- [X] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

2024-04-15 13:50 UTC, andrewfullard approved these changes

2024-04-15 13:52 UTC, andrewfullard requested changes
The only thing that could be changed are the labels on the wavelength x-axis. They show a mu symbol after the numbers that is confusing.

2024-04-18 13:52 UTC, atharva-2001 commented
@andrewfullard I changed them to exponential format as they were earlier, I'm afraid I didn't know what units the wavelengths were saved in, which was required to convert it to angstroms. If the current change is not alright I can investigate, do you want me to do that?

2024-04-18 14:30 UTC, andrewfullard commented
I think it's fine

2024-04-18 14:30 UTC, andrewfullard approved these changes

2024-04-18 14:31 UTC, merged